apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: classifier-sample
  namespace: default
spec:
  annotations:
    seldon.io/rest-timeout: "60"
    seldon.io/grpc-timeout: "60"
  protocol: seldon
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: yevhenk10s/model-monitoring:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'
          - name: WANDB_API_KEY
            value: 061dc0c4c510ff84584bd05674e492de2053d9da
          - name: WANDB_PROJECT
            value: artifact-storage
          imagePullPolicy: Always

    graph:
      name: classifier
      type: MODEL
    name: model
    replicas: 1