apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 10
