apiVersion : apps/v1
kind: Deployment
metadata:
  name: nlp-deployment
  labels:
    app : my-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: nlp-app
  template:
    metadata:
      labels:
        project: nlp-app   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : api-container
          image: yevhenk10s/bert-api:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: nlp-service
  labels:
    env  : prod
    owner: yevhen
spec:
  selector:
    project: nlp-app    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80    # Port on Load Balancer
      targetPort: 5000  # Port on POD
  type: LoadBalancer