name: week-5-test-serving-fastapi-ci

on:
  push:
    branches:
      - 'week-5-serving-fastapi'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install Requirements
        run: |
          pip3 install -r ./week-5-serving-fastapi/requirements.txt
        
      - name: Run Tests
        run: |
          cd ./week-5-serving-fastapi
          python -m pytest -s .
